# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d66ac73fee944ecc88e0c1027bdb4f9e4c88332c11c54a975df841f91c14d5c752910799cd6233e56e5892665f68e8c5e65cc9851da4d376e2b4f41c443e32

test:
  secret_key_base: d92804aefbfc7120d7d8f272974b87e32b952e0c81d68d32b13f79cc511568d5beae4dcd94fc141af6ab2e45e42a0fe341aa6dcf48f16b5984b25110898c6a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
